#!/bin/sh

input=/var/log/hjemmenett-battery-status.log
filename=battery-graph.png

(
    echo set xdata time
    echo set timefmt \"%s\"
    echo set format x \"%Y\"
    echo set datafile separator \",\"
    echo set title \'ACPI Battery Graph\'
    echo set ylabel \'Percent\'
    echo set xlabel \'Year\'
    echo set grid
    echo set term png
    echo set output \"$filename\"
    echo plot "\"$input\" using 1:(100 * \$8 / \$7) smooth unique axis x1y1 title \"Battery level %\" with lines linewidth 1 linecolor rgb 'grey',\"$input\" using 1:(100 * \$6 / \$7) smooth unique axis x1y1 title \"Battery full capasity %\" with lines linewidth 1 linecolor rgb 'red',\"$input\" using 1:(100 * \$7 / \$7) smooth unique axis x1y1 title \"Battery design capasity %\" with lines linewidth 1 linecolor rgb 'black'"

) | gnuplot
echo "PNG graph $filename created."
