#!/bin/sh
# License: GNU Public License v2 or later at your choice.

input=/var/log/hjemmenett-battery-status.log
filename="${1}"

# manufacturer,model_name,technology
type=$(head -2 "$input" | tail -1 | cut -d, -f2-4 | tr , " ")

(
    echo set xdata time
    echo set timefmt \"%s\"
    echo set format x \"%Y\"
    echo set datafile separator \",\"
    echo set title \'Battery statistics $type\'
    echo set ylabel \'Percent\'
    echo set xlabel \'Year\'
    echo set grid
    if [ "$filename" ]; then
        echo set term png
        echo set output \"$filename\"
    fi
    echo plot "\"$input\" using 1:(100 * \$8 / \$7) smooth unique axis x1y1 title \"Battery level %\" with lines linewidth 0.1 linecolor rgb 'grey',\"$input\" using 1:(100 * \$6 / \$7) smooth unique axis x1y1 title \"Battery full capacity %\" with lines linewidth 1 linecolor rgb 'red',\"$input\" using 1:(100 * \$7 / \$7) smooth unique axis x1y1 title \"Battery design capacity %\" with lines linewidth 1 linecolor rgb 'black'"

) | gnuplot -p

if [ "$filename" ] ; then
    echo "PNG graph $filename created."
fi
