#!/bin/sh
# Action script to collect battery status just before and just after
# going to sleep.
#
# Copyright: Copyright (c) 2013 Petter Reinholdtsen
# License:   GPL-2+
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "${1}" in
        hibernate|resume|thaw)
		if [ -x /usr/sbin/collect-battery-status ]; then
		    /usr/sbin/collect-battery-status
		fi
                ;;
esac
